version: 2

models:
  - name: sensor_counts
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: date_time
        tests:
          - not_null
          - is_iso_format
      - name: sensor_id
        tests:
          - not_null
      - name: sensor_name
        tests:
          - not_null
      - name: hourly_count
        tests:
          - not_null

  - name: sensor_reference_data
    columns:
      - name: location_id
        tests:
          - not_null
          - unique
      - name: sensor_description
        tests:
          - not_null
      - name: sensor_name
      - name: installation_date
        tests:
          - not_null
          - is_date_format
      - name: note
      - name: location_type
        tests:
          - not_null
          - accepted_values:
              values: ['Indoor', 'Outdoor', 'Indoor Blix', 'Outdoor Blix']
      - name: status
        tests:
          - not_null
          - accepted_values:
              values: ['A']
      - name: direction_1
        tests:
          - accepted_values:
              values: ['North', 'South', 'East', 'West', 'In', 'Out']
      - name: direction_2
        tests:
          - accepted_values:
              values: ['North', 'South', 'East', 'West', 'In', 'Out']
      - name: latitude
        tests:
          - not_null
      - name: longitude
        tests:
          - not_null
      - name: location
  
  - name: report_top_10_locations_by_day
    columns:
      - name: date
        tests:
          - not_null
          - is_date_format
      - name: rank
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
      - name: sensor_id
        tests:
          - not_null
      - name: location_name
        tests:
          - not_null
      - name: daily_count
        tests:
          - not_null