pedestrian_analysis_raw_profile:
  outputs:
    dev:
      database: awsdatacatalog
      region_name: ap-southeast-2
      s3_data_dir: s3://pedestrian-analysis-working-bucket/raw
      s3_staging_dir: s3://huy-nguyen-00001-audit-logs/athena-logs/
      schema: pedestrian_analysis_raw
      threads: 2
      type: athena
  target: dev

pedestrian_analysis_report_profile:
  outputs:
    dev:
      database: awsdatacatalog
      region_name: ap-southeast-2
      s3_data_dir: s3://pedestrian-analysis-working-bucket/report
      s3_staging_dir: s3://huy-nguyen-00001-audit-logs/athena-logs/
      schema: pedestrian_analysis_report
      threads: 2
      type: athena
  target: dev

pedestrian_analysis_profile:
  outputs:
    dev:
      database: awsdatacatalog
      region_name: ap-southeast-2
      s3_data_dir: s3://pedestrian-analysis-working-bucket/report
      s3_staging_dir: s3://huy-nguyen-00001-audit-logs/athena-logs/
      schema: pedestrian_analysis
      threads: 2
      type: athena
  target: dev