name: CDK Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Install pip
        run: |
          sudo apt install python3-pip
          python -m pip install --upgrade pip setuptools wheel

      - name: Install AWS CLI and CDK
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
          npm install -g aws-cdk
          pip install aws-cdk-lib

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: Deploy to AWS
        run: |
          cdk synth
          cdk bootstrap
          cdk deploy --require-approval never
        env:
          CDK_DEPLOY_REGION: ap-southeast-2
          CDK_DEPLOY_ACCOUNT: 632753217422
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET_NAME: pedestrian-analysis-working-bucket
          CITY_OF_MELBOURNE_API_KEY: ${{ secrets.CITY_OF_MELBOURNE_API_KEY }}
