name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy_cdk:
    runs-on: ubuntu-latest
    steps:

      - name: Install pip
        run: |
          sudo apt install python3-pip
          python -m pip install --upgrade pip setuptools wheel

      # - name: Install AWS CLI
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y awscli

      # - name: Install CDK
      #   run: npm install -g aws-cdk

      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Python Packages
        run: pip install -r ${{ github.workspace }}/requirements.txt

      # - name: Set up Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '14.x'

      # - name: Install dependencies
      #   run: | 
      #     npm install -g aws-cdk@2.76.0
      #     cdk --version

      - name: Install Apache Maven
        run: |
          wget https://aws-glue-etl-artifacts.s3.amazonaws.com/glue-common/apache-maven-3.6.0-bin.tar.gz
          tar -xvf apache-maven-3.6.0-bin.tar.gz
          export PATH=$PATH:$(pwd)/apache-maven-3.6.0/bin
      - name: Install Apache Spark
        run: |
          wget https://aws-glue-etl-artifacts.s3.amazonaws.com/glue-1.0/spark-2.4.3-bin-hadoop2.8.tgz
          tar -xvf spark-2.4.3-bin-hadoop2.8.tgz
          export SPARK_HOME=$(pwd)/spark-2.4.3-bin-hadoop2.8
          export PATH=$PATH:$SPARK_HOME/bin
      - name: Pytests
        run: |
          pip install pytest pytest-cov
          pytest tests

      # - name: Deploy to AWS
      #   run: |
      #     cdk synth
      #     cdk deploy --require-approval never
      #   env:
      #     AWS_ACCOUNT_ID: 632753217422
      #     AWS_REGION: ap-southeast-2
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     BUCKET_NAME: pedestrian-analysis-working-bucket
      #     CITY_OF_MELBOURNE_API_KEY: ${{ secrets.CITY_OF_MELBOURNE_API_KEY }}

      # - name: Run Glue Jobs
      #   run: python ${{ github.workspace }}/run-glue.py
      #   env:
      #     AWS_ACCOUNT_ID: 632753217422
      #     AWS_REGION: ap-southeast-2
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     BUCKET_NAME: pedestrian-analysis-working-bucket
      #     CITY_OF_MELBOURNE_API_KEY: ${{ secrets.CITY_OF_MELBOURNE_API_KEY }}

      # - name: Run DBT tests
      #   run: |
      #     dbt test \
      #       --project-dir ${{ github.workspace }}/pa_dbt \
      #       --profiles-dir ${{ github.workspace }}/pa_dbt/profiles \
      #       --profile pedestrian_analysis_profile
      #   env:
      #     AWS_ACCOUNT_ID: 632753217422
      #     AWS_REGION: ap-southeast-2
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
